### ISSUE TITLE
can sptm be used for the short texts

### ISSUE THREAD

**Issue by youngornever** [Rochan-A/sptm#2]
i want to analysis the topics of the utterances of daily dialogues.

**Comment by Rochan-A** [comment]
Hey,

I'm really sorry for the late replay. I got caught up with some other commitments.

Technically, if you have a corpus that contains dialogues, it should be able to predict the next sentence spoken as long as it can be clustered under a topic.

Usually, the longer the sentence, the better is the topic clustering. However, if the dialogues are distinct enough, the length of the sentences shouldn't really be an issue.  

-Rochan
